/*
 * FacileThings API
 *
 * This is the OpenAPI for `app.facilethings.com`.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: im@strrl.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StuffWrapperStuffProject {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl StuffWrapperStuffProject {
    pub fn new() -> StuffWrapperStuffProject {
        StuffWrapperStuffProject {
            name: None,
        }
    }
}


